apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: fluentd
  labels:
    app: aggregator
    app.kubernetes.io/component: aggregator
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentd
    helm.sh/chart: fluentd-3.6.2
  name: fluentd-aggregator
  namespace: monitoring
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9880
    protocol: TCP
    targetPort: http
  - name: tcp
    port: 24224
    protocol: TCP
    targetPort: tcp
  selector:
    app.kubernetes.io/component: aggregator
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/name: fluentd
  sessionAffinity: None
  type: ClusterIP
