apiVersion: v1
data:
  fluentd.conf: |2

    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    # TCP input to receive logs from the forwarders
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # Send the logs to the standard output
    <match **>
      @type elasticsearch
      include_tag_key true
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      reload_connections false
      reconnect_on_error true
      reload_on_failure true
      index_name monitoring-log
      logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'kube'}"
      logstash_format true
      slow_flush_log_threshold 100
      request_timeout 15s
      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        total_limit_size 512MB
        chunk_limit_size 32MB
        chunk_full_threshold 0.9
        flush_mode interval
        flush_interval 10s
        flush_thread_count 4
        retry_type exponential_backoff
        retry_timeout 1h
        retry_max_interval 30
        overflow_action drop_oldest_chunk
      </buffer>
    </match>
kind: ConfigMap
metadata:
  annotations:
  name: elasticsearch-output
  namespace: monitoring
