apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: ppims
  labels:
    app: config
  name: config-cip-svc
spec:
  ports:
  - name: config-cip-svc
    port: 8092
    targetPort: 8092
    protocol: TCP
  selector:
    app: config
  type: ClusterIP
status:
  loadBalancer: {}
