apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-common
  name: common-svc
spec:
  ports:
  - name: common-out-port
    port: 9003
    targetPort: 9003
    nodePort: 30035
    protocol: TCP
  selector:
    app: ngpims-common
  type: NodePort
status:
  loadBalancer: {}
