apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: ppims
  labels:
    app: eureka-server
  name: eureka-server-svc
spec:
  ports:
  - name: eureka-server-out-port
    port: 8761
    protocol: TCP
    targetPort: 8761
    nodePort: 30010
  selector:
    app: eureka-server
  type: NodePort
status:
  loadBalancer: {}
