apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gateway-cip-svc
  namespace: ppims
spec:
  ports:
  - name: gateway-in-port        
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: ngpims-gateway
  type: ClusterIP
status:
  loadBalancer: {}
