apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gateway-svc
  namespace: ppims
spec:
  ports:
  - name: gateway-out-port
    port: 8081
    targetPort: 8081
    nodePort: 30020
    protocol: TCP
  selector:
    app: ngpims-gateway
  type: NodePort
status:
  loadBalancer: {}
