apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-hr
  name: hr-cip-svc
spec:
  ports:
  - name: hr-in-port
    port: 9005
    targetPort: 9005
    protocol: TCP
  selector:
    app: ngpims-hr
  type: ClusterIP
status:
  loadBalancer: {}
