apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-recruitment
  name: recruitment-svc
spec:
  ports:
  - name: recruitment-out-port
    port: 9002
    targetPort: 9002
    nodePort: 30030
    protocol: TCP
  selector:
    app: ngpims-recruitment
  type: NodePort
status:
  loadBalancer: {}
