apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-recruitment
  name: recruitment-cip-svc
spec:
  ports:
  - name: recruitment-in-port
    port: 9002
    targetPort: 9002
    protocol: TCP
  selector:
    app: ngpims-recruitment
  type: ClusterIP
status:
  loadBalancer: {}
