apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-training
  name: training-svc
spec:
  ports:
  - name: training-out-port
    port: 9006
    targetPort: 9006
    nodePort: 30050
    protocol: TCP
  selector:
    app: ngpims-training
  type: NodePort
status:
  loadBalancer: {}
