apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-uaa
  name: uaa-cip-svc
spec:
  ports:
  - name: uaa-in-port
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: ngpims-uaa
  type: ClusterIP
status:
  loadBalancer: {}
