route:
  group_by: [cluster]
  receiver: 'slack'
#  routes:
#  # Send severity=slack alerts to slack.
#  - match:
#      severity: slack
#    receiver: slack_general

receivers:
- name: slack
  slack_configs:
  - send_resolved: true
    username: 'shoeb.ahmed'
    channel: 'docker-prometheus'
    api_url: 'https://hooks.slack.com/services/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'
             
#route:
#  group_by: [Alertname]
#  # Send all notifications to me.
#  receiver: email-me
#
#receivers:
#- name: email-me
#  email_configs:
#  - to: 'shoeb.off@gmail.com'
#    from: 'shoeb.off@gmail.com'
#    smarthost: smtp.gmail.com:587
#    auth_username: 'shoeb.off'
#    auth_identity: 'shoeb.off'
#    auth_password: '####'