apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hydrus-dev-pod-hpa
  namespace: hydrus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hydrus-dev-pod
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

