apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hydrus-dev-pod-vpa
  namespace: hydrus
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       hydrus-dev-pod
  updatePolicy:
    updateMode: "Auto"
