apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-react-acl-ui
  name: acl-ui-svc
spec:
  ports:
  - name: acl-ui-out-port
    port: 3000
    targetPort: 3000
    nodePort: 31025
    protocol: TCP
  selector:
    app: ngpims-react-acl-ui
  type: NodePort
status:
  loadBalancer: {}
