apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-react-action-center-ui
  name: action-ui-svc
spec:
  ports:
  - name: action-ui-out-port
    port: 3000
    targetPort: 3000
    nodePort: 31050
    protocol: TCP
  selector:
    app: ngpims-react-action-center-ui
  type: NodePort
status:
  loadBalancer: {}
