apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-react-hr-ui
  name: hr-ui-svc
spec:
  ports:
  - name: hr-ui-out-port
    port: 3000
    targetPort: 3000
    nodePort: 31045
    protocol: TCP
  selector:
    app: ngpims-react-hr-ui
  type: NodePort
status:
  loadBalancer: {}
