apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-react-leave-ui
  name: leave-ui-svc
spec:
  ports:
  - name: leave-ui-out-port
    port: 3000
    targetPort: 3000
    nodePort: 31035
    protocol: TCP
  selector:
    app: ngpims-react-leave-ui
  type: NodePort
status:
  loadBalancer: {}
