apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-react-recruit-ui
  name: recruit-ui-svc
spec:
  ports:
  - name: recruit-ui-out-port
    port: 3000
    targetPort: 3000
    nodePort: 31030
    protocol: TCP
  selector:
    app: ngpims-react-recruit-ui
  type: NodePort
status:
  loadBalancer: {}
