apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-react-special-activity-ui
  name: special-ui-svc
spec:
  ports:
  - name: special-ui-out-port
    port: 3000
    targetPort: 3000
    nodePort: 31055
    protocol: TCP
  selector:
    app: ngpims-react-special-activity-ui
  type: NodePort
status:
  loadBalancer: {}
