apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-react-training-ui
  name: training-ui-svc
spec:
  ports:
  - name: training-ui-out-port
    port: 3000
    targetPort: 3000
    nodePort: 31040
    protocol: TCP
  selector:
    app: ngpims-react-training-ui
  type: NodePort
status:
  loadBalancer: {}
