apiVersion: v1
kind: Service
metadata:
  namespace: ppims
  creationTimestamp: null
  labels:
    app: ngpims-uaa-ui
  name: uaa-ui-svc
spec:
  ports:
  - name: ngpims-ui-out-port
    port: 3000
    targetPort: 3000
    nodePort: 31020
    protocol: TCP
  selector:
    app: ngpims-uaa-ui
  type: NodePort
status:
  loadBalancer: {}
