apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reids-tolerations
  name: reids-tolerations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reids-tolerations
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reids-tolerations
    spec:
      containers:
      - image: redis
        name: redis
        resources: {}
status: {}
