apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: reids-tolerations
  name: reids-tolerations
spec:
  containers:
  - image: redis
    name: reids-tolerations
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"
status: {}
