apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - name: postgres-in-port
    port: 5432
    protocol: TCP
    targetPort: 5432  
  selector:
   app: postgres
