kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-database-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/pv/database"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-database-pvc
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
