apiVersion: v1
kind: Service
metadata:
  name: postgres-out
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - name: postgrers-out-port
    nodePort: 30020
    port: 5432
    protocol: TCP
    targetPort: 5432  
  selector:
   app: postgres
