apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_HOST: postgres
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  #POSTGRES_PASSWORD: p0stGrE@p3$l
