apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: default-backend-service
  namespace: app-space
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: default-backend
  type: ClusterIP
status:
  loadBalancer: {}
